dependencies:
- name: core-api-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.3
- name: core-camera-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
- name: core-monitor-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
- name: core-recogniser-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.79
- name: core-rule-engine-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.3
- name: core-sync-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.3
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: frontend-app
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.29
- name: inventory-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.18
- name: pcluster-standalone
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.10
- name: pcrop-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.7
- name: pcrop-worker
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.15
- name: pdataset-api
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.7
- name: pdataset-worker
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.18
- name: pkube-api
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.38
- name: pmodel-management-api
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.23
- name: product-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.25
- name: proxy-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.56
- name: ptag-api
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.26
- name: ptag-frontend
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.15
- name: ptag-proxy-api
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.4
- name: ptag-watchdog
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.8
- name: ptransaction-watchdog
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.6
- name: transaction-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.12
